apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reporting-role
  namespace: payments
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reporting-rolebinding
  namespace: payments
subjects:
  - kind: ServiceAccount
    name: reporting
    namespace: payments
roleRef:
  kind: Role
  name: reporting-role
  apiGroup: rbac.authorization.k8s.io
