---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCLveF1W7MtzguFsZop+btUlQcBpm2irHwdAsjDL3TfFGd8w/y/GkHiANfSFNQ5zPIo4y01I6nkNgVOlvDsoBA7F8BwlMQwZBtcfOe3LOBpM+S8g7UZIKLFCM/RjJBNc36SECXWsRmTNY0VMnKpIZBMybKMutAcZA8bdLJsLZHZ9w1A2L+cC8Woe3VoXil9XmyJwCgJduXj91BhakoQ3ZSKV1dMN5efAZQGsjnKotNJpBvBPRVqeC4EaLbB0KLaaCj9FEtv51rLgTiDBNntDPI5vlVatFqCI3MWiD5HJdtj0O3MSz0V5pfUYJdz+tqCR3VYdYT1GuyH6/xQkvU8KLiixWJj693DZ/MPl3YCfwdpvoyaf15jmn4GdOpQLSy2mXOY94g0sGRveKzzOMZthOvkwNtVFgtpOGpl8xbpyAMAhdDOPtHrxZCvE8RxrOxnXmVOTmqQoZLPDTn8p3rJICwuJG5iUnP2cfPI9bOKEBIDq8IYflQCNXUQ1WqrCuBGyrHVrW3GAcboraovv8PPDUXN3wk9kcwr84zk1nNDuYpnYQkPetIm20SFDx3fNh7XuWsxSlP4LxECquCvDBLTWuPJxQdpq3rZkzs0H2MIrEvnM964qfnLq6Q+bMPNtocj+tROy3ukngfBV5olHpzMwEO/FNOtSkt71u3UB5MEGLukr5T8aLAlzfiRycxc6r3QZl3/KUKrhL6MoGkmGQ==
    STRIPE_API_KEY: AgCoSRTr9XwjWYa4T29IFPn4o1IuPHRuH9kA7mD+SbgumzoGoyQaW+Ssk6JSXCGWexymTRJ3YfY43PZ0OSdx/rRXVKzsB3RMMVJxg5nM8lkA50milEGBKw21PQ4ViJ+rkpGlHKwfwvE0xIF1+1niRPufBtVYgv23vZRyD0ujqyvWLU09MGNUdh2QQpoW0lusK1Fr9VVxZXbLd3Gu8PPTbTWI6VKxWyKF4zdC2cknw3wy3dV7DkNN4w5BYDmg5Xheks3jNZYR0tNRc+y1/xfqaIgoC6WkAE3+kLS3dhBJIuMIcxp4R1DQK6yEzLJh03+RbdaXAJBfOBsp5oRJ258GfH2CfoQARIJ74NwZKqAdVBya2lU/2L5GNzJQw+fc6W4NH/leOj/+WXTjlw4zbAFI7TFZxK60INsAjwyC1y+Dor32rqLXRJ81XyT33gMLVzW9ZFnaDC9/+4ZNKQhk4OOS/WEHG8fewsi+I0b4bZDcpqLKdDUSjsmScPd+mDhZV7TRmszMtKBuKasqC+Ak0Y+nFHl/Rr5i1fj+GG4Vh8CCDAu46BGn4T2bMGKPizv57ei+4Oq3RZvDVvc/cL5cLZEAeSONU4ReZ7X7UpKWzETn/GmPp5MFfwqiPQkbX7/kTcRD8eW4j9F5YPpg70izBP8wTRGDVCyJ/01NBrLYtH0adT/Ox5rzMcLDZ2H3CIDdJsvLO5s891LDyrS42rfcTRtC05I7Wo6idBzksUHgUXY54w==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
